import type { IndustryProfile } from "./types";

const industries: Record<string, IndustryProfile> = {
  retail: {
    id: "retail",
    name: "Retail",
    description:
      "Brick-and-mortar and e-commerce retailers (10-200 employees). Thin margins, high turnover, inventory-driven.",
    typicalCompanySize: "10-200 employees",
    avgRevenueRange: "$1M-$50M",
    benchmarks: {
      operational: {
        avgOrderProcessingTime: "1-3 days (e-commerce); instant (in-store POS)",
        errorRate: "Shrinkage 1.4-1.6% of sales; cart abandonment 78%",
        employeeProductivity: "$150K-$325K revenue per employee",
        inventoryTurnover: "8-12x/year (grocery 14-20x; apparel 4-6x)",
      },
      sales: {
        customerAcquisitionCost: "$68-$84 (e-commerce); $5-$100 (brick-and-mortar). Up 60% over 5 years",
        customerLifetimeValue: "$200-$600; returning customers = 44% of revenue despite being 21% of base",
        conversionRate: "2.5-3.0% (e-commerce); 20-40% (in-store)",
        churnRate: "25-37% annual; retention 63-75%",
        avgSalesCycleDays: 1,
      },
      financial: {
        profitMargin: "Gross 25-35%; Net 2-5% (grocery 1-3%; specialty 5-8%)",
        revenuePerEmployee: "$150,000-$325,000",
        operatingCostRatio: "COGS 60-75%; Labor 10-20%; Rent 5-10%",
        daysSalesOutstanding: 10,
      },
      hr: {
        employeeTurnoverRate: "60-80% annual — highest among major industries",
        timeToHireDays: 25,
        trainingCostPerEmployee: "$1,046 per learner",
        avgTenureYears: 1.5,
      },
      technology: {
        crmAdoption: "50-65%",
        erpAdoption: "45-55%",
        aiAdoption: "40-50% experimenting or using",
        itSpendPercent: "1.5-3.0% of revenue",
      },
    },
    commonPainPoints: [
      "Inventory management — 55% of retail SMBs hold 20%+ excess stock",
      "Employee turnover at 60-80% drives constant hiring/training costs",
      "Cart abandonment at 78% for e-commerce",
      "Rising customer acquisition costs (up 60% in 5 years)",
      "Thin net margins (2-5%) leave no room for error",
      "Manual inventory counts and spreadsheet-based ordering",
      "Disconnected POS, inventory, and accounting systems",
      "Seasonal demand volatility and overstocking",
    ],
    topAutomationOpportunities: [
      "Inventory forecasting & automatic reorder — reduce excess stock by 20-30%",
      "Customer service chatbot — handle 60-70% of routine inquiries",
      "Email/SMS marketing automation — increase repeat purchase rate by 15-25%",
      "Dynamic pricing — adjust prices based on demand, competition, and inventory levels",
      "Automated invoice processing — save 10-15 hours/week on AP/AR",
      "Employee scheduling optimization — reduce labor costs by 5-10%",
    ],
  },

  manufacturing: {
    id: "manufacturing",
    name: "Manufacturing",
    description:
      "Small to mid-size manufacturers (10-200 employees). High COGS, long DSO, inventory-intensive.",
    typicalCompanySize: "10-200 employees",
    avgRevenueRange: "$2M-$50M",
    benchmarks: {
      operational: {
        avgOrderProcessingTime: "2-7 days order-to-scheduling; 2-8 weeks full lead time",
        errorRate: "Defect rate target <50 PPM; industry average 200-500 PPM. First-pass yield 95%+",
        employeeProductivity: "$175K-$250K revenue per employee; OEE target 85%",
        inventoryTurnover: "8.5x average; top performers 5.6x; laggards 2.0x",
      },
      sales: {
        customerAcquisitionCost: "$500-$2,000 (B2B, varies by product complexity)",
        customerLifetimeValue: "$5,000-$50,000+; LTV:CAC ratio 3:1 to 5:1 target",
        conversionRate: "Website-to-lead 2-4%; lead-to-customer 5-10%",
        churnRate: "10-15% annual — high switching costs drive retention",
        avgSalesCycleDays: 90,
      },
      financial: {
        profitMargin: "Gross 25-35%; Net 5-10%; EBITDA 10-15% (top performers 15%+)",
        revenuePerEmployee: "$175,000-$250,000",
        operatingCostRatio: "COGS 65-75%; Labor 15-25%; Overhead 10-15%",
        daysSalesOutstanding: 52,
      },
      hr: {
        employeeTurnoverRate: "25-40% annual",
        timeToHireDays: 31,
        trainingCostPerEmployee: "$800-$1,200",
        avgTenureYears: 3,
      },
      technology: {
        crmAdoption: "86%",
        erpAdoption: "75-80%",
        aiAdoption: "45-55% using or experimenting",
        itSpendPercent: "1.4-3.2% of revenue",
      },
    },
    commonPainPoints: [
      "55% of SMBs hold at least 20% excess stock (Netstock 2025)",
      "Long DSO (45-60 days) creates cash flow pressure",
      "Quality control — rework costs 5-12% of project value",
      "Supply chain disruptions and single-supplier dependencies",
      "Manual production scheduling and capacity planning",
      "Paper-based quality tracking and compliance documentation",
      "Skilled labor shortage — takes 31 days to fill positions",
      "Disconnected MES/ERP/CRM systems",
    ],
    topAutomationOpportunities: [
      "Demand forecasting — reduce excess inventory by 20-30%, improve turns",
      "Quality inspection (visual AI) — catch defects earlier, reduce rework by 50%+",
      "Automated production scheduling — optimize capacity utilization",
      "Predictive maintenance — reduce unplanned downtime by 30-50%",
      "Invoice/AP automation — reduce DSO by 10-15 days",
      "Supplier management automation — auto-reorder, price comparison",
    ],
  },

  professionalservices: {
    id: "professionalservices",
    name: "Professional Services",
    description:
      "Consulting, accounting, legal, marketing agencies (10-200 employees). People-intensive, utilization-driven.",
    typicalCompanySize: "10-200 employees",
    avgRevenueRange: "$1M-$30M",
    benchmarks: {
      operational: {
        avgOrderProcessingTime: "Project kickoff 1-5 days from contract signing",
        errorRate: "30-40% of projects exceed budget/timeline; rework rate 10-15%",
        employeeProductivity: "Billable utilization 68.9% (target 75%); $199K revenue per consultant",
      },
      sales: {
        customerAcquisitionCost: "$500-$3,000 (varies by specialization)",
        customerLifetimeValue: "$10,000-$100,000+; LTV:CAC 4:1 target",
        conversionRate: "Website-to-lead 3-5%; lead-to-client 20-30%",
        churnRate: "27% median annual; IT/managed services 17%; consulting 15%",
        avgSalesCycleDays: 60,
      },
      financial: {
        profitMargin: "Gross 50-70%; Net 10-20% (healthy). EBITDA fell to 9.8% in 2024 — 5-year low",
        revenuePerEmployee: "$150,000-$250,000 ($199K per consultant)",
        operatingCostRatio: "Labor 55-70% of revenue; Overhead 15-25%",
        daysSalesOutstanding: 45,
      },
      hr: {
        employeeTurnoverRate: "15-20% annual",
        timeToHireDays: 37,
        trainingCostPerEmployee: "$944",
        avgTenureYears: 3.5,
      },
      technology: {
        crmAdoption: "70-80%",
        erpAdoption: "55-65%",
        aiAdoption: "55-65% using or experimenting",
        itSpendPercent: "3-6% of revenue",
      },
    },
    commonPainPoints: [
      "Utilization crisis — billable utilization at 68.9%, below 75% target",
      "EBITDA crashed to 9.8% from 15.4% — 5-year low (SPI 2025)",
      "30-40% of projects exceed budget or timeline",
      "Manual time tracking and project reporting",
      "Proposal/SOW creation takes days of senior staff time",
      "Knowledge silos — expertise locked in individual consultants",
      "Scope creep without proper change management",
      "DSO 30-60 days strains cash flow",
    ],
    topAutomationOpportunities: [
      "Proposal/SOW generation (AI) — reduce creation time from days to hours",
      "Time tracking automation — improve utilization visibility by 10-15%",
      "Project health monitoring (AI) — predict overruns before they happen",
      "Automated invoicing & collections — reduce DSO by 10-20 days",
      "Knowledge base / AI assistant — capture and share institutional knowledge",
      "Lead scoring & nurture automation — improve lead-to-client conversion",
    ],
  },

  technology: {
    id: "technology",
    name: "Technology / SaaS",
    description:
      "Software companies and SaaS providers (10-200 employees). High margins, high churn, growth-focused.",
    typicalCompanySize: "10-200 employees",
    avgRevenueRange: "$500K-$50M ARR",
    benchmarks: {
      operational: {
        avgOrderProcessingTime: "Instant (self-serve); 3-14 days (enterprise onboarding)",
        errorRate: "Uptime SLA 99.9%+; bug escape 1-5 per release; support resolution 4-24h",
        employeeProductivity: "$130K revenue per employee (median private SaaS); $283K (public)",
      },
      sales: {
        customerAcquisitionCost: "$702 average SMB SaaS; $2.00 cost per ARR dollar",
        customerLifetimeValue: "$2,000-$15,000 SMB LTV; LTV:CAC 3:1 minimum",
        conversionRate: "Visitor-to-trial 3-5%; trial-to-paid 25-60%; visitor-to-customer 1.1-2.5%",
        churnRate: "SMB monthly 3-7%; SMB annual 31-58%; enterprise annual 5-7%. 43% of losses in first 90 days",
        avgSalesCycleDays: 40,
      },
      financial: {
        profitMargin: "Gross 75-85%; Net -10% to 15% (varies by growth stage). Rule of 40 benchmark",
        revenuePerEmployee: "$130K (median private); $283K (median public)",
        operatingCostRatio: "S&M 30-50%; R&D 20-30%; G&A 10-20%; COGS 15-25%",
        daysSalesOutstanding: 37,
      },
      hr: {
        employeeTurnoverRate: "12-20% annual",
        timeToHireDays: 45,
        trainingCostPerEmployee: "$1,000-$1,500",
        avgTenureYears: 2.5,
      },
      technology: {
        crmAdoption: "94%",
        erpAdoption: "60-70%",
        aiAdoption: "75-83% experimenting or using",
        itSpendPercent: "8-15%+ of revenue",
      },
    },
    commonPainPoints: [
      "SMB churn devastating — 31-58% annual, with 43% of losses in first 90 days",
      "CAC rising 14% year-over-year; acquisition costs up 60% over 5 years",
      "Engineering talent scarce — 45 days average to fill positions",
      "Customer onboarding too manual — high-touch doesn't scale",
      "Support ticket volume growing faster than team",
      "Feature prioritization disconnected from revenue impact",
      "Manual billing, dunning, and subscription management",
      "Sales & marketing attribution unclear",
    ],
    topAutomationOpportunities: [
      "Customer onboarding automation — reduce time-to-value, cut 90-day churn",
      "AI-powered support — deflect 40-60% of Tier 1 tickets",
      "Churn prediction model — identify at-risk accounts 30-60 days before cancellation",
      "Automated billing & dunning — recover 10-15% of failed payments",
      "Lead scoring & sales automation — improve pipeline velocity",
      "AI code review & testing — accelerate release cycles by 20-30%",
    ],
  },

  healthcare: {
    id: "healthcare",
    name: "Healthcare",
    description:
      "Private practices, clinics, healthcare service providers (10-200 employees). Heavily regulated, labor-intensive.",
    typicalCompanySize: "10-200 employees",
    avgRevenueRange: "$1M-$30M",
    benchmarks: {
      operational: {
        avgOrderProcessingTime: "Patient wait 18-24 min; appointment-to-followup 7-14 days",
        errorRate: "Medical errors 3-5% of admissions; claim denial 5-10%; first-pass acceptance 90-95% target",
        employeeProductivity: "$400K-$800K+ revenue per provider; 18-25 patients per provider per day",
      },
      sales: {
        customerAcquisitionCost: "$247-$1,435 per new patient (pediatrics ~$155; cosmetic ~$610)",
        customerLifetimeValue: "$10,000-$20,000 per patient; LTV:CAC 3:1 target",
        conversionRate: "Website-to-appointment 3-5%; appointment-to-patient 60-80%",
        churnRate: "17-25% annual patient attrition; retention 75-83%",
        avgSalesCycleDays: 14,
      },
      financial: {
        profitMargin: "Gross 40-60%; Net 2-8% (private practice); health systems near breakeven",
        revenuePerEmployee: "$100,000-$200,000 (staff); up to $800K+ (per provider)",
        operatingCostRatio: "Labor 50-60%; Medical supplies 10-15%; Overhead 20-30%. Workforce costs rose 5.6% in 2025",
        daysSalesOutstanding: 57,
      },
      hr: {
        employeeTurnoverRate: "19.5% overall; RNs 27.1%; ICU/ER up to 35%",
        timeToHireDays: 49,
        trainingCostPerEmployee: "$1,200-$2,000 (compliance, certifications, CE)",
        avgTenureYears: 3,
      },
      technology: {
        crmAdoption: "82%",
        erpAdoption: "55-65%",
        aiAdoption: "45-55% using or experimenting",
        itSpendPercent: "4-7% of revenue",
      },
    },
    commonPainPoints: [
      "Longest time-to-hire (49 days) among major industries",
      "Nurse turnover 27% — critical staffing shortages",
      "Claim denials 5-10% — revenue leakage from billing errors",
      "DSO 45-70 days — slow insurance reimbursements",
      "Paper-based patient intake and manual data entry",
      "Compliance burden — HIPAA, state regulations, accreditation",
      "Patient no-show rate 15-30% destroys scheduling efficiency",
      "Workforce costs rising 5.6% annually",
    ],
    topAutomationOpportunities: [
      "Patient scheduling & reminders — reduce no-shows by 30-50%",
      "Claims processing automation — improve first-pass acceptance to 95%+",
      "AI-assisted clinical documentation — save 2-3 hours per provider per day",
      "Patient intake digitization — eliminate manual data entry",
      "Automated insurance verification — reduce claim denials",
      "Predictive staffing — optimize schedules based on patient volume patterns",
    ],
  },

  foodhospitality: {
    id: "foodhospitality",
    name: "Food & Hospitality",
    description:
      "Restaurants, cafes, catering, hotels (10-200 employees). Ultra-thin margins, highest turnover, perishable inventory.",
    typicalCompanySize: "10-200 employees",
    avgRevenueRange: "$500K-$10M",
    benchmarks: {
      operational: {
        avgOrderProcessingTime: "5-15 min (dine-in); 30-45 min (delivery). Table turnover 45-90 min",
        errorRate: "Order accuracy 85-95%; food waste 4-10% of purchases",
        employeeProductivity: "$50K-$80K revenue per employee; $35-$70 sales per labor hour",
        inventoryTurnover: "24-36x/year (perishables turned every 1-2 weeks)",
      },
      sales: {
        customerAcquisitionCost: "$10-$50; loyalty programs $1-$5 per member to maintain",
        customerLifetimeValue: "$500-$3,000; loyalty customers spend 15-25% more",
        conversionRate: "Walk-by-to-dine-in 5-15%; online order 3-8%",
        churnRate: "40-60% annual; 84% stick with brands due to loyalty programs",
        avgSalesCycleDays: 1,
      },
      financial: {
        profitMargin: "Gross 60-70%; Net 3-5% (10% top performers). Food COGS 28-35%; Labor 25-40%",
        revenuePerEmployee: "$50,000-$80,000",
        operatingCostRatio: "Food 28-35%; Labor 25-40% (full-service 36-40%); Occupancy 6-10%",
        daysSalesOutstanding: 5,
      },
      hr: {
        employeeTurnoverRate: "75% average (good: 50-60%). Cost: $5,864 per employee turnover",
        timeToHireDays: 21,
        trainingCostPerEmployee: "$500-$821",
        avgTenureYears: 1,
      },
      technology: {
        crmAdoption: "30-40%",
        erpAdoption: "20-30%",
        aiAdoption: "30-40% using or experimenting",
        itSpendPercent: "2-4% of revenue",
      },
    },
    commonPainPoints: [
      "Highest employee turnover at 75% — constant hiring/training cycle",
      "Razor-thin net margins (3-5%) — no room for waste",
      "Food waste at 4-10% of purchases directly hits bottom line",
      "Manual scheduling in Excel creates conflicts and overtime",
      "Disconnected POS, inventory, and accounting systems",
      "Inconsistent customer experience across shifts/locations",
      "No data on customer preferences or visit patterns",
      "Compliance with health codes and food safety manual and paper-based",
    ],
    topAutomationOpportunities: [
      "Employee scheduling optimization — reduce labor costs 5-10%, cut overtime",
      "Inventory tracking & waste reduction — save 2-5% of food costs",
      "Online ordering & loyalty automation — increase repeat visits 15-25%",
      "Automated tip/payroll processing — save 5-10 hours/week",
      "Kitchen display system — improve order accuracy to 98%+",
      "Review management automation — monitor and respond to online reviews",
    ],
  },

  construction: {
    id: "construction",
    name: "Construction",
    description:
      "General and specialty contractors (10-200 employees). Project-based, long DSO, lowest tech adoption.",
    typicalCompanySize: "10-200 employees",
    avgRevenueRange: "$2M-$50M",
    benchmarks: {
      operational: {
        avgOrderProcessingTime: "Bid-to-award 30-90 days; project mobilization 2-4 weeks",
        errorRate: "Rework 5-12% of project cost; safety rate 2.5-3.5 per 100 workers (OSHA)",
        employeeProductivity: "$200K-$400K revenue per employee; billable target 85%+",
        inventoryTurnover: "6-10x for materials; just-in-time delivery common",
      },
      sales: {
        customerAcquisitionCost: "$1,000-$5,000+ (relationship-based; referrals dominate)",
        customerLifetimeValue: "$50,000-$500,000+; LTV:CAC 3:1 to 10:1",
        conversionRate: "Bid-to-win 10-25%; website lead conversion 2-4%",
        churnRate: "15-25% annual; strong repeat in commercial, more transactional in residential",
        avgSalesCycleDays: 120,
      },
      financial: {
        profitMargin: "Gross 12-16% (GC); 15-25% (specialty). Net 5-8% (well-managed)",
        revenuePerEmployee: "$200,000-$400,000",
        operatingCostRatio: "Labor 25-40%; Materials 30-45%; Overhead 8-15%; Equipment 5-10%",
        daysSalesOutstanding: 75,
      },
      hr: {
        employeeTurnoverRate: "20-30% avg; up to 57-73% for skilled trades. Cost: 30-150% of salary",
        timeToHireDays: 13,
        trainingCostPerEmployee: "$800-$1,500 (safety, OSHA, apprenticeships)",
        avgTenureYears: 3,
      },
      technology: {
        crmAdoption: "40-50%",
        erpAdoption: "35-45%",
        aiAdoption: "25-35% using or experimenting",
        itSpendPercent: "1-3% of revenue — lowest among major industries",
      },
    },
    commonPainPoints: [
      "Longest DSO (60-90+ days) — severe cash flow pressure",
      "Lowest tech adoption among all industries",
      "Rework costs 5-12% of project value",
      "Skilled trade shortage — turnover up to 57-73%",
      "Paper-based project tracking, timesheets, and safety logs",
      "Change orders poorly documented — margin erosion",
      "Bid estimation inaccurate — too many underbids or overbids",
      "Subcontractor management is manual and chaotic",
    ],
    topAutomationOpportunities: [
      "Bid estimation (AI) — improve accuracy, reduce underbids/overbids",
      "Digital timesheets & payroll — save 10-15 hours/week, reduce errors",
      "Project management automation — real-time progress tracking",
      "Invoice & payment automation — reduce DSO by 15-25 days",
      "Safety compliance digitization — automated OSHA reporting",
      "Material procurement automation — auto-reorder, price tracking",
    ],
  },
};

export default industries;
